/* LanguageParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. LanguageParserTokenManager.java */
package compiler.parser;
import java.util.List;
import java.util.ArrayList;

/** Token Manager. */
@SuppressWarnings ("unused")
public class LanguageParserTokenManager implements LanguageParserConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x8000000L) != 0L)
            return 7;
         if ((active0 & 0x3fffff0L) != 0L)
         {
            jjmatchedKind = 48;
            return 0;
         }
         return -1;
      case 1:
         if ((active0 & 0xf000L) != 0L)
            return 0;
         if ((active0 & 0x3ff0ff0L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 1;
            }
            return 0;
         }
         return -1;
      case 2:
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x3ff0df0L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 2;
            return 0;
         }
         return -1;
      case 3:
         if ((active0 & 0x4008a0L) != 0L)
            return 0;
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x3bf0550L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 3;
            }
            return 0;
         }
         return -1;
      case 4:
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x3bd0550L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 4;
            return 0;
         }
         return -1;
      case 5:
         if ((active0 & 0x200140L) != 0L)
            return 0;
         if ((active0 & 0xc0000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x3910410L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 5;
            }
            return 0;
         }
         return -1;
      case 6:
         if ((active0 & 0x10L) != 0L)
            return 0;
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0xc0000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x3110400L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 6;
            return 0;
         }
         return -1;
      case 7:
         if ((active0 & 0x3110400L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 7;
            return 0;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0xc0000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x3010400L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 8;
            return 0;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x100000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0xc0000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x3000400L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 9;
            return 0;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x100000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x10000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xc0000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x400L) != 0L)
            return 0;
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x100000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x10000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x3000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 10;
            return 0;
         }
         return -1;
      case 11:
         if ((active0 & 0x3000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         if ((active0 & 0x100000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x10000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active0 & 0x3000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         if ((active0 & 0x100000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x10000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 13:
         if ((active0 & 0x3000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         if ((active0 & 0x10000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active0 & 0x3000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 15:
         if ((active0 & 0x3000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 16:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 17:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 18:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 19:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 20:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 21:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 22:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 23:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 24:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 25:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 26:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 27:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 28:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 29:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 30:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      case 31:
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos < 10)
            {
               jjmatchedKind = 48;
               jjmatchedPos = 10;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 44;
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 37:
         jjmatchedKind = 31;
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 38:
         return jjStopAtPos(0, 42);
      case 42:
         jjmatchedKind = 28;
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 43:
         return jjStopAtPos(0, 26);
      case 45:
         return jjStartNfaWithStates_0(0, 27, 7);
      case 46:
         return jjStopAtPos(0, 41);
      case 47:
         return jjStopAtPos(0, 29);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x2800000000L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      case 62:
         return jjMoveStringLiteralDfa1_0(0x5000000000L);
      case 91:
         return jjStopAtPos(0, 39);
      case 93:
         return jjStopAtPos(0, 40);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x10e000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x3010600L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1010L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x820020L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x400080L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x200100L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0xc0000L);
      case 124:
         return jjStopAtPos(0, 43);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 37:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 32);
         break;
      case 42:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(1, 30);
         break;
      case 60:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 61:
         if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 33);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 34);
         break;
      case 62:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x3830420L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x200110L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0xa00L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x4c0080L);
      case 83:
      case 115:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(1, 12, 0);
         else if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xc000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0xc200L);
      case 61:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(2, 37);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(2, 38);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x120020L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x10400L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x200110L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x400080L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x4400L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L);
      case 69:
      case 101:
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 7;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0xc00010L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x10040L);
      case 76:
      case 108:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 5, 0);
         return jjMoveStringLiteralDfa4_0(active0, 0x3100000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x200100L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0xc0200L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 89:
      case 121:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 0);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa5_0(active0, 0x420000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x3808000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x10010L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x200100L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa6_0(active0, 0xc0000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 69:
      case 101:
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 8;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x200010L);
      case 71:
      case 103:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 6, 0);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x600L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x14000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x3408000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x820000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa7_0(active0, 0xa00000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x3050000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x400L);
      case 82:
      case 114:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(6, 4, 0);
         break;
      case 83:
      case 115:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(6, 9);
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x180000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x3814400L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x210000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x3080400L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000L);
      case 83:
      case 115:
         if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(8, 17);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa10_0(active0, 0x50000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x408000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x3000400L);
      case 83:
      case 115:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(9, 19);
         return jjMoveStringLiteralDfa10_0(active0, 0x200000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(10, 15);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000L);
      case 78:
      case 110:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(10, 10, 0);
         return jjMoveStringLiteralDfa11_0(active0, 0x3000000L);
      case 83:
      case 115:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(10, 23);
         break;
      case 84:
      case 116:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(10, 14);
         else if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(10, 22);
         return jjMoveStringLiteralDfa11_0(active0, 0x50000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa12_0(active0, 0x3000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa12_0(active0, 0x50000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x50000L);
      case 83:
      case 115:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(12, 20);
         break;
      case 84:
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(12, 21);
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         return jjMoveStringLiteralDfa14_0(active0, 0x1000000L);
      case 83:
      case 115:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(13, 16);
         else if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(13, 18);
         break;
      case 89:
      case 121:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa15_0(active0, 0x1000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(15, 25);
         break;
      case 83:
      case 115:
         return jjMoveStringLiteralDfa16_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
static private int jjMoveStringLiteralDfa16_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 84:
      case 116:
         return jjMoveStringLiteralDfa17_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
static private int jjMoveStringLiteralDfa17_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa18_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
static private int jjMoveStringLiteralDfa18_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa19_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
static private int jjMoveStringLiteralDfa19_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 84:
      case 116:
         return jjMoveStringLiteralDfa20_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
static private int jjMoveStringLiteralDfa20_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0);
      return 20;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa21_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(19, active0);
}
static private int jjMoveStringLiteralDfa21_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(19, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0);
      return 21;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa22_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(20, active0);
}
static private int jjMoveStringLiteralDfa22_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(20, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, active0);
      return 22;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa23_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(21, active0);
}
static private int jjMoveStringLiteralDfa23_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(21, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(22, active0);
      return 23;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa24_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(22, active0);
}
static private int jjMoveStringLiteralDfa24_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(22, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(23, active0);
      return 24;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa25_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(23, active0);
}
static private int jjMoveStringLiteralDfa25_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(23, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(24, active0);
      return 25;
   }
   switch(curChar)
   {
      case 86:
      case 118:
         return jjMoveStringLiteralDfa26_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(24, active0);
}
static private int jjMoveStringLiteralDfa26_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(24, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(25, active0);
      return 26;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa27_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(25, active0);
}
static private int jjMoveStringLiteralDfa27_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(25, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(26, active0);
      return 27;
   }
   switch(curChar)
   {
      case 82:
      case 114:
         return jjMoveStringLiteralDfa28_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(26, active0);
}
static private int jjMoveStringLiteralDfa28_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(26, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(27, active0);
      return 28;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa29_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(27, active0);
}
static private int jjMoveStringLiteralDfa29_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(27, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(28, active0);
      return 29;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa30_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(28, active0);
}
static private int jjMoveStringLiteralDfa30_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(28, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(29, active0);
      return 30;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa31_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(29, active0);
}
static private int jjMoveStringLiteralDfa31_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(29, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(30, active0);
      return 31;
   }
   switch(curChar)
   {
      case 76:
      case 108:
         return jjMoveStringLiteralDfa32_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(30, active0);
}
static private int jjMoveStringLiteralDfa32_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(30, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(31, active0);
      return 32;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(32, 24);
         break;
      default :
         break;
   }
   return jjStartNfa_0(31, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 7;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 7:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(3, 4); }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 45)
                        kind = 45;
                     { jjCheckNAdd(2); }
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 45)
                        kind = 45;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAddTwoStates(2, 3); }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAdd(0); }
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  { jjCheckNAdd(0); }
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  { jjCheckNAdd(2); }
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 4:
                  if (curChar == 46)
                     { jjCheckNAdd(5); }
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(5); }
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  { jjCheckNAddStates(0, 2); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 0:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  kind = 48;
                  { jjCheckNAdd(0); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 7 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, "\53", 
"\55", "\52", "\57", "\52\52", "\45", "\45\45", "\75\75", "\41\75", "\74\74", 
"\76\76", "\74\74\75", "\76\76\75", "\133", "\135", "\56", "\46", "\174", "\41", null, 
null, null, null, null, null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   2, 3, 4, 
};

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public LanguageParserTokenManager(JavaCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public LanguageParserTokenManager (JavaCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(JavaCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 7; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(JavaCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, 
};
static final long[] jjtoToken = {
   0x17ffffffffff1L, 
};
static final long[] jjtoSkip = {
   0xeL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    static protected JavaCharStream  input_stream;

    static private final int[] jjrounds = new int[7];
    static private final int[] jjstateSet = new int[2 * 7];
    private static final StringBuilder jjimage = new StringBuilder();
    private static StringBuilder image = jjimage;
    private static int jjimageLen;
    private static int lengthOfMatch;
    static protected int curChar;
}
